<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="​Автоматизированный алгоритм выбора антидепрессанта для терапии депрессивного эпизода у больных ишемической болезнью сердца​">
    <meta name="description" content="">
    <title>Главная</title>
    <title>Автоматизированный алгоритм выбора антидепрессанта для терапии депрессивного эпизода у больных ишемической болезнью сердца</title>
    <style type="text/css">
        .custom-btn {
            width: 130px;
            height: 40px;
            color: #fff;
            border-radius: 5px;
            padding: 10px 25px;
            font-family: 'Lato', sans-serif;
            font-weight: 500;
            background: transparent;
            cursor: pointer;
            transition: all 0.3s ease;
            position: relative;
            display: inline-block;
            box-shadow:inset 2px 2px 2px 0px rgba(255,255,255,.5),
            7px 7px 20px 0px rgba(0,0,0,.1),
            4px 4px 5px 0px rgba(0,0,0,.1);
            outline: none;
        }
        .btn-8 {
            background-color: #f0ecfc;
            background-image: linear-gradient(315deg, #f0ecfc 0%, #c797eb 74%);
            line-height: 42px;
            padding: 0;
            border: none;
        }
    </style>
</head>
<body>
<h1 class="u-custom-font u-font-montserrat u-text u-text-grey-75 u-text-1"> Автоматизированный алгоритм выбора антидепрессанта для терапии депрессивного эпизода у больных ишемической болезнью сердца </h1>
<ol class="u-align-justify u-text u-text-2">
    <li>В первой
        графе («шаги алгоритма») поставьте «да» напротив выбранной Вами группы
        антидепрессантов, а затем и антидепрессанта, с Вашей точки зрения наиболее
        подходящих для конкретного пациента с ишемической болезнью сердца и
        диагностированным депрессивным расстройством.<br>
    </li>
    <li> Далее
        последовательно анализируйте каждый из ниже представленных «шагов алгоритма»,
        отмечая каким-либо образом (например, «V»)
        желаемый эффект для конкретного пациента, а затем – и один, выбранный Вами из
        предложенной группы, антидепрессант.</li>
    <li> Подсчитайте
        количество вариантов «да» для каждого из антидепрессантов. 3 препарата,
        набравших максимальное количество выборов, являются оптимальными для данного
        пациента с ИБС и выявленным депрессивным расстройством.</li>
    <li>Уточните
        для выбранного антидепрессанта относительные противопоказания и взаимодействия
        с другими препаратами, принимаемыми пациентом в соответствии с инструкцией к
        применению.<br>
    </li>
</ol>
<center><button class="custom-btn btn-8"><span>Рассчет</span></button></center>
</body>
</html>