<!DOCTYPE html>
<html>
<head>
    <title>Результат работы алгоритма</title>
</head>
<body>
<h1 align="center">Результат работы алгоритма</h1><hr>
<#--<#list effects as effect>-->
<#--    <table class="table">-->
<#--        <thead>-->
<#--        <tr>-->
<#--            <th scope="col">id</th>-->
<#--            <th scope="col">Description</th>-->
<#--            <th scope="col">Capital</th>-->
<#--        </tr>-->
<#--        </thead>-->
<#--        <tbody>-->
<#--        <tr th:each="country : ${effects}">-->
<#--            <td th:text="${effect.id}"></td>-->
<#--            <td th:text="${effect.description}"></td>-->
<#--            <td th:text="${effect.capital}"></td>-->
<#--        </tr>-->
<#--        </tbody>-->
<#--    </table>-->
<#--</#list>-->

</body>
</html>